In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('call_activity.csv')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [3]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [4]:
df.tail()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [5]:
df.head(20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False

In [7]:
type(df)

pandas.DataFrame

In [8]:
df.State()

TypeError: 'Series' object is not callable

In [9]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: str

In [10]:
df["State"]

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: str

In [11]:
type(df['International plan'])

pandas.Series

In [12]:
newDict = {
    'Name' : ['santhosh','sandhiya','monisha'],
    'description': ['data engineer','Java Developer','CA'],
}

nf = pd.DataFrame.from_dict(newDict)

In [13]:
nf

       Name     description
0  santhosh   data engineer
1  sandhiya  Java Developer
2   monisha              CA

In [14]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='str')

In [15]:
df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [16]:
df.dtypes

State                         str
Account length              int64
Area code                   int64
International plan            str
Voice mail plan               str
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [17]:
df['Total night minutes']

0       244.7
1       254.4
2       162.6
3       196.9
4       186.9
        ...
3328    279.1
3329    191.3
3330    191.9
3331    139.2
3332    241.4
Name: Total night minutes, Length: 3333, dtype: float64

In [18]:
df['Total night minutes'].head()

0    244.7
1    254.4
2    162.6
3    196.9
4    186.9
Name: Total night minutes, dtype: float64

In [19]:
df['State','Total night minutes','Churn'].tail()

KeyError: ('State', 'Total night minutes', 'Churn')

In [21]:
df[['State','Total night minutes','Churn']].tail()

     State  Total night minutes  Churn
3328    AZ                279.1  False
3329    WV                191.3  False
3330    RI                191.9  False
3331    CT                139.2  False
3332    TN                241.4  False

In [22]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [23]:
df['Total intl calls'].unique()

array([ 3,  5,  7,  6,  4,  2,  9, 19,  1, 10, 15,  8, 11,  0, 12, 13, 18,
       14, 16, 20, 17])

In [24]:
df[df['Total intl calls'] == 3 ]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
26,WY,57,408,No,Yes,39,213.0,115.0,36.21,191.1,112.0,16.24,182.7,115.0,8.22,9.5,3,2.57,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3297,ME,148,408,No,Yes,33,241.7,84.0,41.09,165.8,84.0,14.09,160.6,80.0,7.23,11.3,3,3.05,1.0,False
3300,SC,111,415,No,Yes,21,127.1,94.0,21.61,228.3,116.0,19.41,166.7,108.0,7.50,7.1,3,1.92,1.0,False
3302,LA,75,510,Yes,No,0,153.2,78.0,26.04,210.8,99.0,17.92,153.5,100.0,6.91,7.8,3,2.11,1.0,False
3306,AL,106,408,No,Yes,29,83.6,131.0,14.21,203.9,131.0,17.33,229.5,73.0,10.33,8.1,3,2.19,1.0,False
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True

In [26]:
df[(df['Total intl calls'] == 3) & (df['International plan'] == 'Yes')]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
135,AL,91,510,Yes,No,0,129.9,112.0,22.08,173.3,83.0,14.73,247.2,130.0,11.12,11.2,3,3.02,3.0,False
184,VA,170,510,Yes,No,0,259.9,68.0,44.18,245.0,122.0,20.83,134.4,121.0,6.05,8.4,3,2.27,3.0,False
254,TX,97,415,Yes,No,0,143.7,117.0,24.43,273.0,82.0,23.21,178.3,81.0,8.02,10.9,3,2.94,0.0,False
269,MA,118,408,Yes,No,0,160.0,123.0,27.20,175.4,96.0,14.91,184.8,99.0,8.32,9.9,3,2.67,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,NY,131,408,Yes,No,0,122.3,83.0,20.79,118.8,94.0,10.10,147.9,95.0,6.66,13.7,3,3.70,3.0,True
2989,MI,108,408,Yes,No,0,115.1,114.0,19.57,211.3,70.0,17.96,136.1,85.0,6.12,13.8,3,3.73,2.0,True
3031,KY,64,415,Yes,No,0,146.7,83.0,24.94,148.3,91.0,12.61,238.6,69.0,10.74,12.5,3,3.38,3.0,False
3210,TN,93,510,Yes,No,0,168.4,114.0,28.63,276.0,127.0,23.46,196.2,48.0,8.83,11.4,3,3.08,1.0,False
3302,LA,75,510,Yes,No,0,153.2,78.0,26.04,210.8,99.0,17.92,153.5,100.0,6.91,7.8,3,2.11,1.0,False

In [27]:
df[(df['Total intl calls'] == 3) | (df['International plan'] == 'Yes')]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [28]:
df.ilog[9]

AttributeError: 'DataFrame' object has no attribute 'ilog'

In [29]:
df.ilog(9)

AttributeError: 'DataFrame' object has no attribute 'ilog'

In [30]:
df.iLog[9]

AttributeError: 'DataFrame' object has no attribute 'iLog'

In [31]:
df.ilac[9]

AttributeError: 'DataFrame' object has no attribute 'ilac'

In [32]:
df.iloc[9]

State                        WV
Account length              141
Area code                   415
International plan          Yes
Voice mail plan             Yes
Number vmail messages        37
Total day minutes         258.6
Total day calls            84.0
Total day charge          43.96
Total eve minutes         222.0
Total eve calls           111.0
Total eve charge          18.87
Total night minutes       326.4
Total night calls          97.0
Total night charge        14.69
Total intl minutes         11.2
Total intl calls              5
Total intl charge          3.02
Customer service calls      0.0
Churn                     False
Name: 9, dtype: object

In [33]:
df.iloc[0,0]

'KS'

In [34]:
df.iloc[1,9]

np.float64(195.5)

In [35]:
df.iloc[9:19]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False

In [36]:
df.iloc[:,0]

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: str

In [37]:
stateDf = df.copy()

In [38]:
stateDf.set_index('State',inplace=True)

In [39]:
stateDf

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [40]:
stateDf[KS]

NameError: name 'KS' is not defined

In [41]:
stateDf['KS']

KeyError: 'KS'

In [42]:
stateDf.loc['KS']

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
KS,70,408,No,No,0,232.1,122.0,39.46,292.3,112.0,24.85,201.2,112.0,9.05,0.0,0,0.00,3.0,False
KS,92,408,Yes,No,0,62.6,111.0,10.64,180.6,126.0,15.35,221.7,80.0,9.98,10.4,2,2.81,1.0,True
KS,137,408,No,No,0,205.9,88.0,35.00,209.3,86.0,17.79,289.9,84.0,13.05,14.5,4,3.92,2.0,False
KS,132,415,No,No,0,83.4,110.0,14.18,232.2,137.0,19.74,146.7,114.0,6.60,7.6,5,2.05,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KS,164,510,No,Yes,30,238.8,100.0,40.60,230.0,121.0,19.55,206.3,66.0,9.28,13.2,8,3.56,1.0,False
KS,101,415,No,No,0,231.3,87.0,39.32,224.7,88.0,19.10,214.6,69.0,9.66,7.2,7,1.94,1.0,False
KS,127,415,No,Yes,24,154.8,69.0,26.32,177.2,105.0,15.06,207.6,102.0,9.34,9.0,4,2.43,1.0,False
KS,57,415,No,No,0,158.1,117.0,26.88,115.2,149.0,9.79,182.4,92.0,8.21,11.8,7,3.19,0.0,False
KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True

In [43]:
stateDf.reset_index()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [44]:
df.isnull()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3329,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3330,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3331,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3332,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [45]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [46]:
df.dropna(inplace=True)

In [47]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [48]:
df.drop('Total eve minutes ',axis=1)

KeyError: "['Total eve minutes '] not found in axis"

In [49]:
df.drop('Total eve minutes',axis=1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [50]:
df['collab'] = df['Total intl calls'] + df['Customer service calls']

In [51]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,8.0
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,7.0
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,8.0
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,12.0
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,4.0

In [52]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0

In [53]:
df.iloc[0,0] = 'SS'

In [54]:
df.head(1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,SS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.7,1.0,False,4.0

In [55]:
df.to_csv("santhosh.csv")

In [56]:
df = pd.read_csv('santhosh.csv')

In [57]:
df

,Unnamed: 0,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,0,SS,128,415,No,Yes,25,265.1,110.0,45.07,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,1,OH,107,415,No,Yes,26,161.6,123.0,27.47,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,2,NJ,137,415,No,No,0,243.4,114.0,41.38,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,3,OH,84,408,Yes,No,0,299.4,71.0,50.90,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,4,OK,75,415,Yes,No,0,166.7,113.0,28.34,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3302,3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,8.0
3303,3329,WV,68,415,No,No,0,231.1,57.0,39.29,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,7.0
3304,3330,RI,28,510,No,No,0,180.8,109.0,30.74,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,8.0
3305,3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,12.0
3306,3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,4.0

In [58]:
df.to_json()

'{"Unnamed: 0":{"0":0,"1":1,"2":2,"3":3,"4":4,"5":5,"6":7,"7":8,"8":9,"9":10,"10":11,"11":23,"12":24,"13":25,"14":26,"15":27,"16":28,"17":30,"18":39,"19":40,"20":41,"21":42,"22":43,"23":44,"24":45,"25":46,"26":47,"27":48,"28":49,"29":50,"30":51,"31":52,"32":53,"33":54,"34":55,"35":56,"36":57,"37":58,"38":59,"39":60,"40":61,"41":62,"42":63,"43":64,"44":65,"45":66,"46":67,"47":68,"48":69,"49":70,"50":71,"51":72,"52":73,"53":74,"54":75,"55":76,"56":77,"57":78,"58":79,"59":80,"60":81,"61":82,"62":83,"63":84,"64":85,"65":86,"66":87,"67":88,"68":89,"69":90,"70":91,"71":92,"72":93,"73":94,"74":95,"75":96,"76":97,"77":98,"78":99,"79":100,"80":101,"81":102,"82":103,"83":104,"84":105,"85":106,"86":107,"87":108,"88":109,"89":110,"90":111,"91":112,"92":113,"93":114,"94":115,"95":116,"96":117,"97":118,"98":119,"99":120,"100":121,"101":122,"102":123,"103":124,"104":125,"105":126,"106":127,"107":128,"108":129,"109":130,"110":131,"111":132,"112":133,"113":134,"114":135,"115":136,"116":137,"117":143,"118":144,"119":145,"120":146,"121":147,"122":148,"123":149,"124":150,"125":151,"126":152,"127":153,"128":154,"129":155,"130":156,"131":157,"132":158,"133":159,"134":160,"135":161,"136":162,"137":163,"138":164,"139":165,"140":166,"141":167,"142":168,"143":169,"144":170,"145":171,"146":172,"147":173,"148":174,"149":175,"150":176,"151":177,"152":178,"153":179,"154":180,"155":181,"156":182,"157":183,"158":184,"159":185,"160":186,"161":187,"162":188,"163":189,"164":190,"165":191,"166":192,"167":193,"168":194,"169":195,"170":196,"171":197,"172":198,"173":199,"174":200,"175":201,"176":202,"177":203,"178":204,"179":205,"180":206,"181":207,"182":208,"183":209,"184":210,"185":211,"186":212,"187":213,"188":214,"189":215,"190":216,"191":217,"192":218,"193":219,"194":220,"195":221,"196":222,"197":223,"198":224,"199":225,"200":226,"201":227,"202":228,"203":229,"204":230,"205":231,"206":232,"207":233,"208":234,"209":235,"210":236,"211":237,"212":238,"213":239,"214":240,"215":241,"216":242,"217":243,"218":244,"219":245,"220":246,"221":247,"222":248,"223":249,"224":250,"225":251,"226":252,"227":253,"228":254,"229":255,"230":256,"231":257,"232":258,"233":259,"234":260,"235":261,"236":262,"237":263,"238":264,"239":265,"240":266,"241":267,"242":268,"243":269,"244":270,"245":271,"246":272,"247":273,"248":274,"249":275,"250":276,"251":277,"252":278,"253":279,"254":280,"255":281,"256":282,"257":283,"258":284,"259":285,"260":286,"261":287,"262":288,"263":289,"264":290,"265":291,"266":292,"267":293,"268":294,"269":295,"270":296,"271":297,"272":298,"273":299,"274":300,"275":301,"276":302,"277":303,"278":304,"279":305,"280":306,"281":307,"282":308,"283":309,"284":310,"285":311,"286":312,"287":313,"288":314,"289":315,"290":316,"291":317,"292":318,"293":319,"294":320,"295":321,"296":322,"297":323,"298":324,"299":325,"300":326,"301":327,"302":328,"303":329,"304":330,"305":331,"306":332,"307":333,"308":334,"309":335,"310":336,"311":337,"312":338,"313":339,"314":340,"315":341,"316":342,"317":343,"318":344,"319":345,"320":346,"321":347,"322":348,"323":349,"324":350,"325":351,"326":352,"327":353,"328":354,"329":355,"330":356,"331":357,"332":358,"333":359,"334":360,"335":361,"336":362,"337":363,"338":364,"339":365,"340":366,"341":367,"342":368,"343":369,"344":370,"345":371,"346":372,"347":373,"348":374,"349":375,"350":376,"351":377,"352":378,"353":379,"354":380,"355":381,"356":382,"357":383,"358":384,"359":385,"360":386,"361":387,"362":388,"363":389,"364":390,"365":391,"366":392,"367":393,"368":394,"369":395,"370":396,"371":397,"372":398,"373":399,"374":400,"375":401,"376":402,"377":403,"378":404,"379":405,"380":406,"381":407,"382":408,"383":409,"384":410,"385":411,"386":412,"387":413,"388":414,"389":415,"390":416,"391":417,"392":418,"393":419,"394":420,"395":421,"396":422,"397":423,"398":424,"399":425,"400":426,"401":427,"402":428,"403":429,"404":430,"405":431,"406":432,"407":433,"408":434,"409":435,"410":436,"411":437,"412":438,"413":439,"414":440,"415":441,"416":442,"417":443,"418":444,"419":445,"420":446,"421":447,"422":448,"423":449,"424":450,"425":451,"426":452,"427":453,"428":454,"429":455,"430":456,"431":457,"432":458,"433":459,"434":460,"435":461,"436":462,"437":463,"438":464,"439":465,"440":466,"441":467,"442":468,"443":469,"444":470,"445":471,"446":472,"447":473,"448":474,"449":475,"450":476,"451":477,"452":478,"453":479,"454":480,"455":481,"456":482,"457":483,"458":484,"459":485,"460":486,"461":487,"462":488,"463":489,"464":490,"465":491,"466":492,"467":493,"468":494,"469":495,"470":496,"471":497,"472":498,"473":499,"474":500,"475":501,"476":502,"477":503,"478":504,"479":505,"480":506,"481":507,"482":508,"483":509,"484":510,"485":511,"486":512,"487":513,"488":514,"489":515,"490":516,"491":517,"492":518,"493":519,"494":520,"495":521,"496":522,"497":523,"498":524,"499":525,"500":526,"501":527,"502":528,"503":529,"504":530,"505":531,"506":532,"507":533,"508":534,"509":535,"510":536,"511":537,"512":538,"513":539,"514":540,"515":541,"516":542,"517":543,"518":544,"519":545,"520":546,"521":547,"522":548,"523":549,"524":550,"525":551,"526":552,"527":553,"528":554,"529":555,"530":556,"531":557,"532":558,"533":559,"534":560,"535":561,"536":562,"537":563,"538":564,"539":565,"540":566,"541":567,"542":568,"543":569,"544":570,"545":571,"546":572,"547":573,"548":574,"549":575,"550":576,"551":577,"552":578,"553":579,"554":580,"555":581,"556":582,"557":583,"558":584,"559":585,"560":586,"561":587,"562":588,"563":589,"564":590,"565":591,"566":592,"567":593,"568":594,"569":595,"570":596,"571":597,"572":598,"573":599,"574":600,"575":601,"576":602,"577":603,"578":604,"579":605,"580":606,"581":607,"582":608,"583":609,"584":610,"585":611,"586":612,"587":613,"588":614,"589":615,"590":616,"591":617,"592":618,"593":619,"594":620,"595":621,"596":622,"597":623,"598":624,"599":625,"600":626,"601":627,"602":628,"603":629,"604":630,"605":631,"606":632,"607":633,"608":634,"609":635,"610":636,"611":637,"612":638,"613":639,"614":640,"615":641,"616":642,"617":643,"618":644,"619":645,"620":646,"621":647,"622":648,"623":649,"624":650,"625":651,"626":652,"627":653,"628":654,"629":655,"630":656,"631":657,"632":658,"633":659,"634":660,"635":661,"636":662,"637":663,"638":664,"639":665,"640":666,"641":667,"642":668,"643":669,"644":670,"645":671,"646":672,"647":673,"648":674,"649":675,"650":676,"651":677,"652":678,"653":679,"654":680,"655":681,"656":682,"657":683,"658":684,"659":685,"660":686,"661":687,"662":688,"663":689,"664":690,"665":691,"666":692,"667":693,"668":694,"669":695,"670":696,"671":697,"672":698,"673":699,"674":700,"675":701,"676":702,"677":703,"678":704,"679":705,"680":706,"681":707,"682":708,"683":709,"684":710,"685":711,"686":712,"687":713,"688":714,"689":715,"690":716,"691":717,"692":718,"693":719,"694":720,"695":721,"696":722,"697":723,"698":724,"699":725,"700":726,"701":727,"702":728,"703":729,"704":730,"705":731,"706":732,"707":733,"708":734,"709":735,"710":736,"711":737,"712":738,"713":739,"714":740,"715":741,"716":742,"717":743,"718":744,"719":745,"720":746,"721":747,"722":748,"723":749,"724":750,"725":751,"726":752,"727":753,"728":754,"729":755,"730":756,"731":757,"732":758,"733":759,"734":760,"735":761,"736":762,"737":763,"738":764,"739":765,"740":766,"741":767,"742":768,"743":769,"744":770,"745":771,"746":772,"747":773,"748":774,"749":775,"750":776,"751":777,"752":778,"753":779,"754":780,"755":781,"756":782,"757":783,"758":784,"759":785,"760":786,"761":787,"762":788,"763":789,"764":790,"765":791,"766":792,"767":793,"768":794,"769":795,"770":796,"771":797,"772":798,"773":799,"774":800,"775":801,"776":802,"777":803,"778":804,"779":805,"780":806,"781":807,"782":808,"783":809,"784":810,"785":811,"786":812,"787":813,"788":814,"789":815,"790":816,"791":817,"792":818,"793":819,"794":820,"795":821,"796":822,"797":823,"798":824,"799":825,"800":826,"801":827,"802":828,"803":829,"804":830,"805":831,"806":832,"807":833,"808":834,"809":835,"810":836,"811":837,"812":838,"813":839,"814":840,"815":841,"816":842,"817":843,"818":844,"819":845,"820":846,"821":847,"822":848,"823":849,"824":850,"825":851,"826":852,"827":853,"828":854,"829":855,"830":856,"831":857,"832":858,"833":859,"834":860,"835":861,"836":862,"837":863,"838":864,"839":865,"840":866,"841":867,"842":868,"843":869,"844":870,"845":871,"846":872,"847":873,"848":874,"849":875,"850":876,"851":877,"852":878,"853":879,"854":880,"855":881,"856":882,"857":883,"858":884,"859":885,"860":886,"861":887,"862":888,"863":889,"864":890,"865":891,"866":892,"867":893,"868":894,"869":895,"870":896,"871":897,"872":898,"873":899,"874":900,"875":901,"876":902,"877":903,"878":904,"879":905,"880":906,"881":907,"882":908,"883":909,"884":910,"885":911,"886":912,"887":913,"888":914,"889":915,"890":916,"891":917,"892":918,"893":919,"894":920,"895":921,"896":922,"897":923,"898":924,"899":925,"900":926,"901":927,"902":928,"903":929,"904":930,"905":931,"906":932,"907":933,"908":934,"909":935,"910":936,"911":937,"912":938,"913":939,"914":940,"915":941,"916":942,"917":943,"918":944,"919":945,"920":946,"921":947,"922":948,"923":949,"924":950,"925":951,"926":952,"927":953,"928":954,"929":955,"930":956,"931":957,"932":958,"933":959,"934":960,"935":961,"936":962,"937":963,"938":964,"939":965,"940":966,"941":967,"942":968,"943":969,"944":970,"945":971,"946":972,"947":973,"948":974,"949":975,"950":976,"951":977,"952":978,"953":979,"954":980,"955":981,"956":982,"957":983,"958":984,"959":985,"960":986,"961":987,"962":988,"963":989,"964":990,"965":991,"966":992,"967":993,"968":994,"969":995,"970":996,"971":997,"972":998,"973":999,"974":1000,"975":1001,"976":1002,"977":1003,"978":1004,"979":1005,"980":1006,"981":1007,"982":1008,"983":1009,"984":1010,"985":1011,"986":1012,"987":1013,"988":1014,"989":1015,"990":1016,"991":1017,"992":1018,"993":1019,"994":1020,"995":1021,"996":1022,"997":1023,"998":1024,"999":1025,"1000":1026,"1001":1027,"1002":1028,"1003":1029,"1004":1030,"1005":1031,"1006":1032,"1007":1033,"1008":1034,"1009":1035,"1010":1036,"1011":1037,"1012":1038,"1013":1039,"1014":1040,"1015":1041,"1016":1042,"1017":1043,"1018":1044,"1019":1045,"1020":1046,"1021":1047,"1022":1048,"1023":1049,"1024":1050,"1025":1051,"1026":1052,"1027":1053,"1028":1054,"1029":1055,"1030":1056,"1031":1057,"1032":1058,"1033":1059,"1034":1060,"1035":1061,"1036":1062,"1037":1063,"1038":1064,"1039":1065,"1040":1066,"1041":1067,"1042":1068,"1043":1069,"1044":1070,"1045":1071,"1046":1072,"1047":1073,"1048":1074,"1049":1075,"1050":1076,"1051":1077,"1052":1078,"1053":1079,"1054":1080,"1055":1081,"1056":1082,"1057":1083,"1058":1084,"1059":1085,"1060":1086,"1061":1087,"1062":1088,"1063":1089,"1064":1090,"1065":1091,"1066":1092,"1067":1093,"1068":1094,"1069":1095,"1070":1096,"1071":1097,"1072":1098,"1073":1099,"1074":1100,"1075":1101,"1076":1102,"1077":1103,"1078":1104,"1079":1105,"1080":1106,"1081":1107,"1082":1108,"1083":1109,"1084":1110,"1085":1111,"1086":1112,"1087":1113,"1088":1114,"1089":1115,"1090":1116,"1091":1117,"1092":1118,"1093":1119,"1094":1120,"1095":1121,"1096":1122,"1097":1123,"1098":1124,"1099":1125,"1100":1126,"1101":1127,"1102":1128,"1103":1129,"1104":1130,"1105":1131,"1106":1132,"1107":1133,"1108":1134,"1109":1135,"1110":1136,"1111":1137,"1112":1138,"1113":1139,"1114":1140,"1115":1141,"1116":1142,"1117":1143,"1118":1144,"1119":1145,"1120":1146,"1121":1147,"1122":1148,"1123":1149,"1124":1150,"1125":1151,"1126":1152,"1127":1153,"1128":1154,"1129":1155,"1130":1156,"1131":1157,"1132":1158,"1133":1159,"1134":1160,"1135":1161,"1136":1162,"1137":1163,"1138":1164,"1139":1165,"1140":1166,"1141":1167,"1142":1168,"1143":1169,"1144":1170,"1145":1171,"1146":1172,"1147":1173,"1148":1174,"1149":1175,"1150":1176,"1151":1177,"1152":1178,"1153":1179,"1154":1180,"1155":1181,"1156":1182,"1157":1183,"1158":1184,"1159":1185,"1160":1186,"1161":1187,"1162":1188,"1163":1189,"1164":1190,"1165":1191,"1166":1192,"1167":1193,"1168":1194,"1169":1195,"1170":1196,"1171":1197,"1172":1198,"1173":1199,"1174":1200,"1175":1201,"1176":1202,"1177":1203,"1178":1204,"1179":1205,"1180":1206,"1181":1207,"1182":1208,"1183":1209,"1184":1210,"1185":1211,"1186":1212,"1187":1213,"1188":1214,"1189":1215,"1190":1216,"1191":1217,"1192":1218,"1193":1219,"1194":1220,"1195":1221,"1196":1222,"1197":1223,"1198":1224,"1199":1225,"1200":1226,"1201":1227,"1202":1228,"1203":1229,"1204":1230,"1205":1231,"1206":1232,"1207":1233,"1208":1234,"1209":1235,"1210":1236,"1211":1237,"1212":1238,"1213":1239,"1214":1240,"1215":1241,"1216":1242,"1217":1243,"1218":1244,"1219":1245,"1220":1246,"1221":1247,"1222":1248,"1223":1249,"1224":1250,"1225":1251,"1226":1252,"1227":1253,"1228":1254,"1229":1255,"1230":1256,"1231":1257,"1232":1258,"1233":1259,"1234":1260,"1235":1261,"1236":1262,"1237":1263,"1238":1264,"1239":1265,"1240":1266,"1241":1267,"1242":1268,"1243":1269,"1244":1270,"1245":1271,"1246":1272,"1247":1273,"1248":1274,"1249":1275,"1250":1276,"1251":1277,"1252":1278,"1253":1279,"1254":1280,"1255":1281,"1256":1282,"1257":1283,"1258":1284,"1259":1285,"1260":1286,"1261":1287,"1262":1288,"1263":1289,"1264":1290,"1265":1291,"1266":1292,"1267":1293,"1268":1294,"1269":1295,"1270":1296,"1271":1297,"1272":1298,"1273":1299,"1274":1300,"1275":1301,"1276":1302,"1277":1303,"1278":1304,"1279":1305,"1280":1306,"1281":1307,"1282":1308,"1283":1309,"1284":1310,"1285":1311,"1286":1312,"1287":1313,"1288":1314,"1289":1315,"1290":1316,"1291":1317,"1292":1318,"1293":1319,"1294":1320,"1295":1321,"1296":1322,"1297":1323,"1298":1324,"1299":1325,"1300":1326,"1301":1327,"1302":1328,"1303":1329,"1304":1330,"1305":1331,"1306":1332,"1307":1333,"1308":1334,"1309":1335,"1310":1336,"1311":1337,"1312":1338,"1313":1339,"1314":1340,"1315":1341,"1316":1342,"1317":1343,"1318":1344,"1319":1345,"1320":1346,"1321":1347,"1322":1348,"1323":1349,"1324":1350,"1325":1351,"1326":1352,"1327":1353,"1328":1354,"1329":1355,"1330":1356,"1331":1357,"1332":1358,"1333":1359,"1334":1360,"1335":1361,"1336":1362,"1337":1363,"1338":1364,"1339":1365,"1340":1366,"1341":1367,"1342":1368,"1343":1369,"1344":1370,"1345":1371,"1346":1372,"1347":1373,"1348":1374,"1349":1375,"1350":1376,"1351":1377,"1352":1378,"1353":1379,"1354":1380,"1355":1381,"1356":1382,"1357":1383,"1358":1384,"1359":1385,"1360":1386,"1361":1387,"1362":1388,"1363":1389,"1364":1390,"1365":1391,"1366":1392,"1367":1393,"1368":1394,"1369":1395,"1370":1396,"1371":1397,"1372":1398,"1373":1399,"1374":1400,"1375":1401,"1376":1402,"1377":1403,"1378":1404,"1379":1405,"1380":1406,"1381":1407,"1382":1408,"1383":1409,"1384":1410,"1385":1411,"1386":1412,"1387":1413,"1388":1414,"1389":1415,"1390":1416,"1391":1417,"1392":1418,"1393":1419,"1394":1420,"1395":1421,"1396":1422,"1397":1423,"1398":1424,"1399":1425,"1400":1426,"1401":1427,"1402":1428,"1403":1429,"1404":1430,"1405":1431,"1406":1432,"1407":1433,"1408":1434,"1409":1435,"1410":1436,"1411":1437,"1412":1438,"1413":1439,"1414":1440,"1415":1441,"1416":1442,"1417":1443,"1418":1444,"1419":1445,"1420":1446,"1421":1447,"1422":1448,"1423":1449,"1424":1450,"1425":1451,"1426":1452,"1427":1453,"1428":1454,"1429":1455,"1430":1456,"1431":1457,"1432":1458,"1433":1459,"1434":1460,"1435":1461,"1436":1462,"1437":1463,"1438":1464,"1439":1465,"1440":1466,"1441":1467,"1442":1468,"1443":1469,"1444":1470,"1445":1471,"1446":1472,"1447":1473,"1448":1474,"1449":1475,"1450":1476,"1451":1477,"1452":1478,"1453":1479,"1454":1480,"1455":1481,"1456":1482,"1457":1483,"1458":1484,"1459":1485,"1460":1486,"1461":1487,"1462":1488,"1463":1489,"1464":1490,"1465":1491,"1466":1492,"1467":1493,"1468":1494,"1469":1495,"1470":1496,"1471":1497,"1472":1498,"1473":1499,"1474":1500,"1475":1501,"1476":1502,"1477":1503,"1478":1504,"1479":1505,"1480":1506,"1481":1507,"1482":1508,"1483":1509,"1484":1510,"1485":1511,"1486":1512,"1487":1513,"1488":1514,"1489":1515,"1490":1516,"1491":1517,"1492":1518,"1493":1519,"1494":1520,"1495":1521,"1496":1522,"1497":1523,"1498":1524,"1499":1525,"1500":1526,"1501":1527,"1502":1528,"1503":1529,"1504":1530,"1505":1531,"1506":1532,"1507":1533,"1508":1534,"1509":1535,"1510":1536,"1511":1537,"1512":1538,"1513":1539,"1514":1540,"1515":1541,"1516":1542,"1517":1543,"1518":1544,"1519":1545,"1520":1546,"1521":1547,"1522":1548,"1523":1549,"1524":1550,"1525":1551,"1526":1552,"1527":1553,"1528":1554,"1529":1555,"1530":1556,"1531":1557,"1532":1558,"1533":1559,"1534":1560,"1535":1561,"1536":1562,"1537":1563,"1538":1564,"1539":1565,"1540":1566,"1541":1567,"1542":1568,"1543":1569,"1544":1570,"1545":1571,"1546":1572,"1547":1573,"1548":1574,"1549":1575,"1550":1576,"1551":1577,"1552":1578,"1553":1579,"1554":1580,"1555":1581,"1556":1582,"1557":1583,"1558":1584,"1559":1585,"1560":1586,"1561":1587,"1562":1588,"1563":1589,"1564":1590,"1565":1591,"1566":1592,"1567":1593,"1568":1594,"1569":1595,"1570":1596,"1571":1597,"1572":1598,"1573":1599,"1574":1600,"1575":1601,"1576":1602,"1577":1603,"1578":1604,"1579":1605,"1580":1606,"1581":1607,"1582":1608,"1583":1609,"1584":1610,"1585":1611,"1586":1612,"1587":1613,"1588":1614,"1589":1615,"1590":1616,"1591":1617,"1592":1618,"1593":1619,"1594":1620,"1595":1621,"1596":1622,"1597":1623,"1598":1624,"1599":1625,"1600":1626,"1601":1627,"1602":1628,"1603":1629,"1604":1630,"1605":1631,"1606":1632,"1607":1633,"1608":1634,"1609":1635,"1610":1636,"1611":1637,"1612":1638,"1613":1639,"1614":1640,"1615":1641,"1616":1642,"1617":1643,"1618":1644,"1619":1645,"1620":1646,"1621":1647,"1622":1648,"1623":1649,"1624":1650,"1625":1651,"1626":1652,"1627":1653,"1628":1654,"1629":1655,"1630":1656,"1631":1657,"1632":1658,"1633":1659,"1634":1660,"1635":1661,"1636":1662,"1637":1663,"1638":1664,"1639":1665,"1640":1666,"1641":1667,"1642":1668,"1643":1669,"1644":1670,"1645":1671,"1646":1672,"1647":1673,"1648":1674,"1649":1675,"1650":1676,"1651":1677,"1652":1678,"1653":1679,"1654":1680,"1655":1681,"1656":1682,"1657":1683,"1658":1684,"1659":1685,"1660":1686,"1661":1687,"1662":1688,"1663":1689,"1664":1690,"1665":1691,"1666":1692,"1667":1693,"1668":1694,"1669":1695,"1670":1696,"1671":1697,"1672":1698,"1673":1699,"1674":1700,"1675":1701,"1676":1702,"1677":1703,"1678":1704,"1679":1705,"1680":1706,"1681":1707,"1682":1708,"1683":1709,"1684":1710,"1685":1711,"1686":1712,"1687":1713,"1688":1714,"1689":1715,"1690":1716,"1691":1717,"1692":1718,"1693":1719,"1694":1720,"1695":1721,"1696":1722,"1697":1723,"1698":1724,"1699":1725,"1700":1726,"1701":1727,"1702":1728,"1703":1729,"1704":1730,"1705":1731,"1706":1732,"1707":1733,"1708":1734,"1709":1735,"1710":1736,"1711":1737,"1712":1738,"1713":1739,"1714":1740,"1715":1741,"1716":1742,"1717":1743,"1718":1744,"1719":1745,"1720":1746,"1721":1747,"1722":1748,"1723":1749,"1724":1750,"1725":1751,"1726":1752,"1727":1753,"1728":1754,"1729":1755,"1730":1756,"1731":1757,"1732":1758,"1733":1759,"1734":1760,"1735":1761,"1736":1762,"1737":1763,"1738":1764,"1739":1765,"1740":1766,"1741":1767,"1742":1768,"1743":1769,"1744":1770,"1745":1771,"1746":1772,"1747":1773,"1748":1774,"1749":1775,"1750":1776,"1751":1777,"1752":1778,"1753":1779,"1754":1780,"1755":1781,"1756":1782,"1757":1783,"1758":1784,"1759":1785,"1760":1786,"1761":1787,"1762":1788,"1763":1789,"1764":1790,"1765":1791,"1766":1792,"1767":1793,"1768":1794,"1769":1795,"1770":1796,"1771":1797,"1772":1798,"1773":1799,"1774":1800,"1775":1801,"1776":1802,"1777":1803,"1778":1804,"1779":1805,"1780":1806,"1781":1807,"1782":1808,"1783":1809,"1784":1810,"1785":1811,"1786":1812,"1787":1813,"1788":1814,"1789":1815,"1790":1816,"1791":1817,"1792":1818,"1793":1819,"1794":1820,"1795":1821,"1796":1822,"1797":1823,"1798":1824,"1799":1825,"1800":1826,"1801":1827,"1802":1828,"1803":1829,"1804":1830,"1805":1831,"1806":1832,"1807":1833,"1808":1834,"1809":1835,"1810":1836,"1811":1837,"1812":1838,"1813":1839,"1814":1840,"1815":1841,"1816":1842,"1817":1843,"1818":1844,"1819":1845,"1820":1846,"1821":1847,"1822":1848,"1823":1849,"1824":1850,"1825":1851,"1826":1852,"1827":1853,"1828":1854,"1829":1855,"1830":1856,"1831":1857,"1832":1858,"1833":1859,"1834":1860,"1835":1861,"1836":1862,"1837":1863,"1838":1864,"1839":1865,"1840":1866,"1841":1867,"1842":1868,"1843":1869,"1844":1870,"1845":1871,"184

In [59]:
df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Unnamed: 0</th>\n      <th>State</th>\n      <th>Account length</th>\n      <th>Area code</th>\n      <th>International plan</th>\n      <th>Voice mail plan</th>\n      <th>Number vmail messages</th>\n      <th>Total day minutes</th>\n      <th>Total day calls</th>\n      <th>Total day charge</th>\n      <th>Total eve minutes</th>\n      <th>Total eve calls</th>\n      <th>Total eve charge</th>\n      <th>Total night minutes</th>\n      <th>Total night calls</th>\n      <th>Total night charge</th>\n      <th>Total intl minutes</th>\n      <th>Total intl calls</th>\n      <th>Total intl charge</th>\n      <th>Customer service calls</th>\n      <th>Churn</th>\n      <th>collab</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>SS</td>\n      <td>128</td>\n      <td>415</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>25</td>\n      <td>265.1</td>\n      <td>110.0</td>\n      <td>45.07</td>\n      <td>197.4</td>\n      <td>99.0</td>\n      <td>16.78</td>\n      <td>244.7</td>\n      <td>91.0</td>\n      <td>11.01</td>\n      <td>10.0</td>\n      <td>3</td>\n      <td>2.70</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>OH</td>\n      <td>107</td>\n      <td>415</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>26</td>\n      <td>161.6</td>\n      <td>123.0</td>\n      <td>27.47</td>\n      <td>195.5</td>\n      <td>103.0</td>\n      <td>16.62</td>\n      <td>254.4</td>\n      <td>103.0</td>\n      <td>11.45</td>\n      <td>13.7</td>\n      <td>3</td>\n      <td>3.70</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>NJ</td>\n      <td>137</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>243.4</td>\n      <td>114.0</td>\n      <td>41.38</td>\n      <td>121.2</td>\n      <td>110.0</td>\n      <td>10.30</td>\n      <td>162.6</td>\n      <td>104.0</td>\n      <td>7.32</td>\n      <td>12.2</td>\n      <td>5</td>\n      <td>3.29</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3</td>\n      <td>OH</td>\n      <td>84</td>\n      <td>408</td>\n      <td>Yes</td>\n      <td>No</td>\n      <td>0</td>\n      <td>299.4</td>\n      <td>71.0</td>\n      <td>50.90</td>\n      <td>61.9</td>\n      <td>88.0</td>\n      <td>5.26</td>\n      <td>196.9</td>\n      <td>89.0</td>\n      <td>8.86</td>\n      <td>6.6</td>\n      <td>7</td>\n      <td>1.78</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>9.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>4</td>\n      <td>OK</td>\n      <td>75</td>\n      <td>415</td>\n      <td>Yes</td>\n      <td>No</td>\n      <td>0</td>\n      <td>166.7</td>\n      <td>113.0</td>\n      <td>28.34</td>\n      <td>148.3</td>\n      <td>122.0</td>\n      <td>12.61</td>\n      <td>186.9</td>\n      <td>121.0</td>\n      <td>8.41</td>\n      <td>10.1</td>\n      <td>3</td>\n      <td>2.73</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>5</td>\n      <td>AL</td>\n      <td>118</td>\n      <td>510</td>\n      <td>Yes</td>\n      <td>No</td>\n      <td>0</td>\n      <td>223.4</td>\n      <td>98.0</td>\n      <td>37.98</td>\n      <td>220.6</td>\n      <td>101.0</td>\n      <td>18.75</td>\n      <td>203.9</td>\n      <td>118.0</td>\n      <td>9.18</td>\n      <td>6.3</td>\n      <td>6</td>\n      <td>1.70</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>7</td>\n      <td>MO</td>\n      <td>147</td>\n      <td>415</td>\n      <td>Yes</td>\n      <td>No</td>\n      <td>0</td>\n      <td>157.0</td>\n      <td>79.0</td>\n      <td>26.69</td>\n      <td>103.1</td>\n      <td>94.0</td>\n      <td>8.76</td>\n      <td>211.8</td>\n      <td>96.0</td>\n      <td>9.53</td>\n      <td>7.1</td>\n      <td>6</td>\n      <td>1.92</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>8</td>\n      <td>LA</td>\n      <td>117</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>184.5</td>\n      <td>97.0</td>\n      <td>31.37</td>\n      <td>351.6</td>\n      <td>80.0</td>\n      <td>29.89</td>\n      <td>215.8</td>\n      <td>90.0</td>\n      <td>9.71</td>\n      <td>8.7</td>\n      <td>4</td>\n      <td>2.35</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>9</td>\n      <td>WV</td>\n      <td>141</td>\n      <td>415</td>\n      <td>Yes</td>\n      <td>Yes</td>\n      <td>37</td>\n      <td>258.6</td>\n      <td>84.0</td>\n      <td>43.96</td>\n      <td>222.0</td>\n      <td>111.0</td>\n      <td>18.87</td>\n      <td>326.4</td>\n      <td>97.0</td>\n      <td>14.69</td>\n      <td>11.2</td>\n      <td>5</td>\n      <td>3.02</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>10</td>\n      <td>IN</td>\n      <td>65</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>129.1</td>\n      <td>137.0</td>\n      <td>21.95</td>\n      <td>228.5</td>\n      <td>83.0</td>\n      <td>19.42</td>\n      <td>208.8</td>\n      <td>111.0</td>\n      <td>9.40</td>\n      <td>12.7</td>\n      <td>6</td>\n      <td>3.43</td>\n      <td>4.0</td>\n      <td>True</td>\n      <td>10.0</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>11</td>\n      <td>RI</td>\n      <td>74</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>187.7</td>\n      <td>127.0</td>\n      <td>31.91</td>\n      <td>163.4</td>\n      <td>148.0</td>\n      <td>13.89</td>\n      <td>196.0</td>\n      <td>94.0</td>\n      <td>8.82</td>\n      <td>9.1</td>\n      <td>5</td>\n      <td>2.46</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>23</td>\n      <td>SC</td>\n      <td>111</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>110.4</td>\n      <td>103.0</td>\n      <td>18.77</td>\n      <td>137.3</td>\n      <td>102.0</td>\n      <td>11.67</td>\n      <td>189.6</td>\n      <td>105.0</td>\n      <td>8.53</td>\n      <td>7.7</td>\n      <td>6</td>\n      <td>2.08</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>24</td>\n      <td>VA</td>\n      <td>132</td>\n      <td>510</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>81.1</td>\n      <td>86.0</td>\n      <td>13.79</td>\n      <td>245.2</td>\n      <td>72.0</td>\n      <td>20.84</td>\n      <td>237.0</td>\n      <td>115.0</td>\n      <td>10.67</td>\n      <td>10.3</td>\n      <td>2</td>\n      <td>2.78</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>2.0</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>25</td>\n      <td>NE</td>\n      <td>174</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>124.3</td>\n      <td>76.0</td>\n      <td>21.13</td>\n      <td>277.1</td>\n      <td>112.0</td>\n      <td>23.55</td>\n      <td>250.7</td>\n      <td>115.0</td>\n      <td>11.28</td>\n      <td>15.5</td>\n      <td>5</td>\n      <td>4.19</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>26</td>\n      <td>WY</td>\n      <td>57</td>\n      <td>408</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>39</td>\n      <td>213.0</td>\n      <td>115.0</td>\n      <td>36.21</td>\n      <td>191.1</td>\n      <td>112.0</td>\n      <td>16.24</td>\n      <td>182.7</td>\n      <td>115.0</td>\n      <td>8.22</td>\n      <td>9.5</td>\n      <td>3</td>\n      <td>2.57</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>3.0</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>27</td>\n      <td>MT</td>\n      <td>54</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>134.3</td>\n      <td>73.0</td>\n      <td>22.83</td>\n      <td>155.5</td>\n      <td>100.0</td>\n      <td>13.22</td>\n      <td>102.1</td>\n      <td>68.0</td>\n      <td>4.59</td>\n      <td>14.7</td>\n      <td>4</td>\n      <td>3.97</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>28</td>\n      <td>MO</td>\n      <td>20</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>190.0</td>\n      <td>109.0</td>\n      <td>32.30</td>\n      <td>258.2</td>\n      <td>84.0</td>\n      <td>21.95</td>\n      <td>181.5</td>\n      <td>102.0</td>\n      <td>8.17</td>\n      <td>6.3</td>\n      <td>6</td>\n      <td>1.70</td>\n      <td>0.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>30</td>\n      <td>IL</td>\n      <td>142</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>84.8</td>\n      <td>95.0</td>\n      <td>14.42</td>\n      <td>136.7</td>\n      <td>63.0</td>\n      <td>11.62</td>\n      <td>250.5</td>\n      <td>148.0</td>\n      <td>11.27</td>\n      <td>14.2</td>\n      <td>6</td>\n      <td>3.83</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>39</td>\n      <td>NJ</td>\n      <td>149</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>140.4</td>\n      <td>94.0</td>\n      <td>23.87</td>\n      <td>271.8</td>\n      <td>92.0</td>\n      <td>23.10</td>\n      <td>188.3</td>\n      <td>108.0</td>\n      <td>8.47</td>\n      <td>11.1</td>\n      <td>9</td>\n      <td>3.00</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>10.0</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>40</td>\n      <td>GA</td>\n      <td>98</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>126.3</td>\n      <td>102.0</td>\n      <td>21.47</td>\n      <td>166.8</td>\n      <td>85.0</td>\n      <td>14.18</td>\n      <td>187.8</td>\n      <td>135.0</td>\n      <td>8.45</td>\n      <td>9.4</td>\n      <td>2</td>\n      <td>2.54</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>41</td>\n      <td>MD</td>\n      <td>135</td>\n      <td>408</td>\n      <td>Yes</td>\n      <td>Yes</td>\n      <td>41</td>\n      <td>173.1</td>\n      <td>85.0</td>\n      <td>29.43</td>\n      <td>203.9</td>\n      <td>107.0</td>\n      <td>17.33</td>\n      <td>122.2</td>\n      <td>78.0</td>\n      <td>5.50</td>\n      <td>14.6</td>\n      <td>15</td>\n      <td>3.94</td>\n      <td>0.0</td>\n      <td>True</td>\n      <td>15.0</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>42</td>\n      <td>AR</td>\n      <td>34</td>\n      <td>510</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>124.8</td>\n      <td>82.0</td>\n      <td>21.22</td>\n      <td>282.2</td>\n      <td>98.0</td>\n      <td>23.99</td>\n      <td>311.5</td>\n      <td>78.0</td>\n      <td>14.02</td>\n      <td>10.0</td>\n      <td>4</td>\n      <td>2.70</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>43</td>\n      <td>ID</td>\n      <td>160</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>85.8</td>\n      <td>77.0</td>\n      <td>14.59</td>\n      <td>165.3</td>\n      <td>110.0</td>\n      <td>14.05</td>\n      <td>178.5</td>\n      <td>92.0</td>\n      <td>8.03</td>\n      <td>9.2</td>\n      <td>4</td>\n      <td>2.48</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>44</td>\n      <td>WI</td>\n      <td>64</td>\n      <td>510</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>154.0</td>\n      <td>67.0</td>\n      <td>26.18</td>\n      <td>225.8</td>\n      <td>118.0</td>\n      <td>19.19</td>\n      <td>265.3</td>\n      <td>86.0</td>\n      <td>11.94</td>\n      <td>3.5</td>\n      <td>3</td>\n      <td>0.95</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>45</td>\n      <td>OR</td>\n      <td>59</td>\n      <td>408</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>28</td>\n      <td>120.9</td>\n      <td>97.0</td>\n      <td>20.55</td>\n      <td>213.0</td>\n      <td>92.0</td>\n      <td>18.11</td>\n      <td>163.1</td>\n      <td>116.0</td>\n      <td>7.34</td>\n      <td>8.5</td>\n      <td>5</td>\n      <td>2.30</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>46</td>\n      <td>MI</td>\n      <td>65</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>211.3</td>\n      <td>120.0</td>\n      <td>35.92</td>\n      <td>162.6</td>\n      <td>122.0</td>\n      <td>13.82</td>\n      <td>134.7</td>\n      <td>118.0</td>\n      <td>6.06</td>\n      <td>13.2</td>\n      <td>5</td>\n      <td>3.56</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>47</td>\n      <td>DE</td>\n      <td>142</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>187.0</td>\n      <td>133.0</td>\n      <td>31.79</td>\n      <td>134.6</td>\n      <td>74.0</td>\n      <td>11.44</td>\n      <td>242.2</td>\n      <td>127.0</td>\n      <td>10.90</td>\n      <td>7.4</td>\n      <td>5</td>\n      <td>2.00</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>48</td>\n      <td>ID</td>\n      <td>119</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>159.1</td>\n      <td>114.0</td>\n      <td>27.05</td>\n      <td>231.3</td>\n      <td>117.0</td>\n      <td>19.66</td>\n      <td>143.2</td>\n      <td>91.0</td>\n      <td>6.44</td>\n      <td>8.8</td>\n      <td>3</td>\n      <td>2.38</td>\n      <td>5.0</td>\n      <td>True</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>49</td>\n      <td>WY</td>\n      <td>97</td>\n      <td>415</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>24</td>\n      <td>133.2</td>\n      <td>135.0</td>\n      <td>22.64</td>\n      <td>217.2</td>\n      <td>58.0</td>\n      <td>18.46</td>\n      <td>70.6</td>\n      <td>79.0</td>\n      <td>3.18</td>\n      <td>11.0</td>\n      <td>3</td>\n      <td>2.97</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>50</td>\n      <td>IA</td>\n      <td>52</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>191.9</td>\n      <td>108.0</td>\n      <td>32.62</td>\n      <td>269.8</td>\n      <td>96.0</td>\n      <td>22.93</td>\n      <td>236.8</td>\n      <td>87.0</td>\n      <td>10.66</td>\n      <td>7.8</td>\n      <td>5</td>\n      <td>2.11</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>51</td>\n      <td>IN</td>\n      <td>60</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>220.6</td>\n      <td>57.0</td>\n      <td>37.50</td>\n      <td>211.1</td>\n      <td>115.0</td>\n      <td>17.94</td>\n      <td>249.0</td>\n      <td>129.0</td>\n      <td>11.21</td>\n      <td>6.8</td>\n      <td>3</td>\n      <td>1.84</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>52</td>\n      <td>VA</td>\n      <td>10</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>186.1</td>\n      <td>112.0</td>\n      <td>31.64</td>\n      <td>190.2</td>\n      <td>66.0</td>\n      <td>16.17</td>\n      <td>282.8</td>\n      <td>57.0</td>\n      <td>12.73</td>\n      <td>11.4</td>\n      <td>6</td>\n      <td>3.08</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>53</td>\n      <td>UT</td>\n      <td>96</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>160.2</td>\n      <td>117.0</td>\n      <td>27.23</td>\n      <td>267.5</td>\n      <td>67.0</td>\n      <td>22.74</td>\n      <td>228.5</td>\n      <td>68.0</td>\n      <td>10.28</td>\n      <td>9.3</td>\n      <td>5</td>\n      <td>2.51</td>\n      <td>2.0</td>\n      <td>False</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>54</td>\n      <td>WY</td>\n      <td>87</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>151.0</td>\n      <td>83.0</td>\n      <td>25.67</td>\n      <td>219.7</td>\n      <td>116.0</td>\n      <td>18.67</td>\n      <td>203.9</td>\n      <td>127.0</td>\n      <td>9.18</td>\n      <td>9.7</td>\n      <td>3</td>\n      <td>2.62</td>\n      <td>5.0</td>\n      <td>True</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>55</td>\n      <td>IN</td>\n      <td>81</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>175.5</td>\n      <td>67.0</td>\n      <td>29.84</td>\n      <td>249.3</td>\n      <td>85.0</td>\n      <td>21.19</td>\n      <td>270.2</td>\n      <td>98.0</td>\n      <td>12.16</td>\n      <td>10.2</td>\n      <td>3</td>\n      <td>2.75</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>35</th>\n      <td>56</td>\n      <td>CO</td>\n      <td>141</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>126.9</td>\n      <td>98.0</td>\n      <td>21.57</td>\n      <td>180.0</td>\n      <td>62.0</td>\n      <td>15.30</td>\n      <td>140.8</td>\n      <td>128.0</td>\n      <td>6.34</td>\n      <td>8.0</td>\n      <td>2</td>\n      <td>2.16</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>3.0</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>57</td>\n      <td>CO</td>\n      <td>121</td>\n      <td>408</td>\n      <td>No</td>\n      <td>Yes</td>\n      <td>30</td>\n      <td>198.4</td>\n      <td>129.0</td>\n      <td>33.73</td>\n      <td>75.3</td>\n      <td>77.0</td>\n      <td>6.40</td>\n      <td>181.2</td>\n      <td>77.0</td>\n      <td>8.15</td>\n      <td>5.8</td>\n      <td>3</td>\n      <td>1.57</td>\n      <td>3.0</td>\n      <td>True</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>58</td>\n      <td>WI</td>\n      <td>68</td>\n      <td>415</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>148.8</td>\n      <td>70.0</td>\n      <td>25.30</td>\n      <td>246.5</td>\n      <td>164.0</td>\n      <td>20.95</td>\n      <td>129.8</td>\n      <td>103.0</td>\n      <td>5.84</td>\n      <td>12.1</td>\n      <td>3</td>\n      <td>3.27</td>\n      <td>3.0</td>\n      <td>False</td>\n      <td>6.0</td>\n    </tr>\n    <tr>\n      <th>38</th>\n      <td>59</td>\n      <td>OK</td>\n      <td>125</td>\n      <td>408</td>\n      <td>No</td>\n      <td>No</td>\n      <td>0</td>\n      <td>229.3</td>\n      <td>103.0</td>\n      <td>38.98</td>\n      <td>177.4</td>\n      <td>126.0</td>\n      <td>15.08</td>\n      <td>189.3</td>\n      <td>95.0</td>\n      <td>8.52</td>\n      <td>12.0</td>\n      <td>8</td>\n      <td>3.24</td>\n      <td>1.0</td>\n      <td>False</td>\n      <td>9.0</td>\n    </tr>\n    <tr>\n      <th>39</th>

In [60]:
del df

In [61]:
df

NameError: name 'df' is not defined

In [62]:
df = pd.read_csv('santhosh.csv')

In [63]:
df

,Unnamed: 0,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,0,SS,128,415,No,Yes,25,265.1,110.0,45.07,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,1,OH,107,415,No,Yes,26,161.6,123.0,27.47,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,2,NJ,137,415,No,No,0,243.4,114.0,41.38,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,3,OH,84,408,Yes,No,0,299.4,71.0,50.90,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,4,OK,75,415,Yes,No,0,166.7,113.0,28.34,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3302,3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,8.0
3303,3329,WV,68,415,No,No,0,231.1,57.0,39.29,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,7.0
3304,3330,RI,28,510,No,No,0,180.8,109.0,30.74,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,8.0
3305,3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,12.0
3306,3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,4.0

In [64]:
df

,Unnamed: 0,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,0,SS,128,415,No,Yes,25,265.1,110.0,45.07,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,1,OH,107,415,No,Yes,26,161.6,123.0,27.47,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,2,NJ,137,415,No,No,0,243.4,114.0,41.38,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,3,OH,84,408,Yes,No,0,299.4,71.0,50.90,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,4,OK,75,415,Yes,No,0,166.7,113.0,28.34,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3302,3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,8.0
3303,3329,WV,68,415,No,No,0,231.1,57.0,39.29,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,7.0
3304,3330,RI,28,510,No,No,0,180.8,109.0,30.74,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,8.0
3305,3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,12.0
3306,3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,4.0

In [65]:
df.drop('Unnamed: 0')

KeyError: "['Unnamed: 0'] not found in axis"

In [66]:
df.drop('Unnamed: 0',axis=1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
0,SS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,4.0
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,4.0
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,5.0
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,9.0
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3302,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,8.0
3303,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,7.0
3304,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,8.0
3305,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,12.0
3306,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,4.0

In [67]:
df[100]

KeyError: 100

In [68]:
df.index(100)

TypeError: 'RangeIndex' object is not callable

In [69]:
df[10:20]

,Unnamed: 0,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
10,11,RI,74,415,No,No,0,187.7,127.0,31.91,...,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False,5.0
11,23,SC,111,415,No,No,0,110.4,103.0,18.77,...,11.67,189.6,105.0,8.53,7.7,6,2.08,2.0,False,8.0
12,24,VA,132,510,No,No,0,81.1,86.0,13.79,...,20.84,237.0,115.0,10.67,10.3,2,2.78,0.0,False,2.0
13,25,NE,174,415,No,No,0,124.3,76.0,21.13,...,23.55,250.7,115.0,11.28,15.5,5,4.19,3.0,False,8.0
14,26,WY,57,408,No,Yes,39,213.0,115.0,36.21,...,16.24,182.7,115.0,8.22,9.5,3,2.57,0.0,False,3.0
15,27,MT,54,408,No,No,0,134.3,73.0,22.83,...,13.22,102.1,68.0,4.59,14.7,4,3.97,3.0,False,7.0
16,28,MO,20,415,No,No,0,190.0,109.0,32.30,...,21.95,181.5,102.0,8.17,6.3,6,1.70,0.0,False,6.0
17,30,IL,142,415,No,No,0,84.8,95.0,14.42,...,11.62,250.5,148.0,11.27,14.2,6,3.83,2.0,False,8.0
18,39,NJ,149,408,No,No,0,140.4,94.0,23.87,...,23.10,188.3,108.0,8.47,11.1,9,3.00,1.0,False,10.0
19,40,GA,98,408,No,No,0,126.3,102.0,21.47,...,14.18,187.8,135.0,8.45,9.4,2,2.54,3.0,False,5.0

In [70]:
df[0,2]

KeyError: (0, 2)

In [71]:
df[1,1]

KeyError: (1, 1)

In [72]:
df.iloc[1,1]

'OH'

In [73]:
df.iloc[10:20]

,Unnamed: 0,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,collab
10,11,RI,74,415,No,No,0,187.7,127.0,31.91,...,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False,5.0
11,23,SC,111,415,No,No,0,110.4,103.0,18.77,...,11.67,189.6,105.0,8.53,7.7,6,2.08,2.0,False,8.0
12,24,VA,132,510,No,No,0,81.1,86.0,13.79,...,20.84,237.0,115.0,10.67,10.3,2,2.78,0.0,False,2.0
13,25,NE,174,415,No,No,0,124.3,76.0,21.13,...,23.55,250.7,115.0,11.28,15.5,5,4.19,3.0,False,8.0
14,26,WY,57,408,No,Yes,39,213.0,115.0,36.21,...,16.24,182.7,115.0,8.22,9.5,3,2.57,0.0,False,3.0
15,27,MT,54,408,No,No,0,134.3,73.0,22.83,...,13.22,102.1,68.0,4.59,14.7,4,3.97,3.0,False,7.0
16,28,MO,20,415,No,No,0,190.0,109.0,32.30,...,21.95,181.5,102.0,8.17,6.3,6,1.70,0.0,False,6.0
17,30,IL,142,415,No,No,0,84.8,95.0,14.42,...,11.62,250.5,148.0,11.27,14.2,6,3.83,2.0,False,8.0
18,39,NJ,149,408,No,No,0,140.4,94.0,23.87,...,23.10,188.3,108.0,8.47,11.1,9,3.00,1.0,False,10.0
19,40,GA,98,408,No,No,0,126.3,102.0,21.47,...,14.18,187.8,135.0,8.45,9.4,2,2.54,3.0,False,5.0

In [74]:
df.iloc[12]

Unnamed: 0                   24
State                        VA
Account length              132
Area code                   510
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes          81.1
Total day calls            86.0
Total day charge          13.79
Total eve minutes         245.2
Total eve calls            72.0
Total eve charge          20.84
Total night minutes       237.0
Total night calls         115.0
Total night charge        10.67
Total intl minutes         10.3
Total intl calls              2
Total intl charge          2.78
Customer service calls      0.0
Churn                     False
collab                      2.0
Name: 12, dtype: object

In [75]:
df[df['State'] == 'CH']

Empty DataFrame
Columns: [Unnamed: 0, State, Account length, Area code, International plan, Voice mail plan, Number vmail messages, Total day minutes, Total day calls, Total day charge, Total eve minutes, Total eve calls, Total eve charge, Total night minutes, Total night calls, Total night charge, Total intl minutes, Total intl calls, Total intl charge, Customer service calls, Churn, collab]
Index: []

[0 rows x 22 columns]